# Generated by Django 4.2.4 on 2023-08-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=80)),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField()),
                ('created_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
